spring:
  datasource:
    username: root
    password: 2364555434
    url: jdbc:mysql://1.117.229.165:3306/gulimall_ums?allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 1.117.229.165:8848

  application:
    name: gulimall-member
  redis:
    host: 1.117.229.165
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000