# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.117.229.165:3306/gulimall_oms?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 2364555434
  #    微服务
  cloud:
    nacos:
      discovery:
        server-addr: 1.117.229.165:8848
  application:
    name: gulimall-order
  rabbitmq:
    host: 1.117.229.165
    port: 5672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: simple
    template:
      mandatory: true
    publisher-returns: true

  redis:
    host: 1.117.229.165
  thymeleaf:
    cache: false
  session:
    store-type: redis
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 9010
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
seata:
  tx-service-group: gulimall-order-seata
  service:
    vgroup-mapping:
      gulimall-order-seata:  default
    disable-global-transaction: false
    grouplist:
      seata-server: 1.117.2291.65:8091
  enabled: true
  application-id: ${spring.application.name}
  enable-auto-data-source-proxy: true
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 1.117.229.165:8848
      cluster: "default"
  config:
    type: file



