spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 1.117.229.165:8848
  thymeleaf:
    cache: false
  redis:
    host: 1.117.229.165
  session:
    store-type: redis
server:
  port: 12000

