server:
  port: 11000

spring:
  datasource:
    username: root
    password: 2364555434
    url: jdbc:mysql://1.117.229.165:3306/gulimall_wms?allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 0
      maximum-pool-size: 5
      minimum-idle: 3

  cloud:
    nacos:
      discovery:
        server-addr: 1.117.229.165:8848
  application:
    name: gulimall-ware

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 1.117.229.165

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.atguigu: debug